import os

files = {
    "frontend/lib/api.ts": """import axios from 'axios';\n\nconst API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';\n\nconst apiClient = axios.create({\n    baseURL: API_URL,\n    headers: {\n        'Content-Type': 'application/json',\n    },\n});\n\napiClient.interceptors.request.use((config) => {\n    const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;\n    if (token) {\n        config.headers.Authorization = `Bearer ${token}`;\n    }\n    return config;\n});\n\nexport const authAPI = {\n    login: async (credentials: any) => {\n        const response = await apiClient.post('/auth/login', credentials);\n        return response.data;\n    },\n};\n\nexport const plansAPI = {\n    getByDate: async (date: string) => {\n        const response = await apiClient.get(`/plans/date/${date}`);\n        return response.data;\n    },\n    markComplete: async (planId: string) => {\n        const response = await apiClient.post(`/plans/${planId}/complete`);\n        return response.data;\n    },\n    addNote: async (planId: string, content: string) => {\n        const response = await apiClient.post(`/plans/${planId}/notes`, { content });\n        return response.data;\n    },\n    getNotes: async (planId: string) => {\n        const response = await apiClient.get(`/plans/${planId}/notes`);\n        return response.data;\n    },\n    getDynamic: async (date: string) => {\n        const response = await apiClient.get(`/plans/date/${date}/dynamic`);\n        return response.data;\n    },\n    topicChat: async (planId: string, message: string, history: any[] = [], sessionId?: string) => {\n        const response = await apiClient.post(`/plans/${planId}/topic-chat`, {\n            message,\n            history,\n            session_id: sessionId,\n        });\n        return response.data;\n    },\n};\n\nexport const chatAPI = {\n    send: async (message: string, sessionId?: string, contextTopic?: string) => {\n        const response = await apiClient.post('/chat', {\n            message,\n            session_id: sessionId,\n            context_topic: contextTopic,\n        });\n        return response.data;\n    },\n    getHistory: async (sessionId: string) => {\n        const response = await apiClient.get(`/chat/history/${sessionId}`);\n        return response.data;\n    },\n    getSessions: async () => {\n        const response = await apiClient.get('/chat/sessions');\n        return response.data;\n    },\n};\n""",
}

for path, content in files.items():
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

print("Restored known frontend files!")
